version: "0.0.1"

networks:
  av-telemetry:
    driver: bridge

services:

  # Zookeeper -- could use a config file, defaults okay for now
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    networks:
      - av-telemetry
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka Server -- needs safe topic creation
  kafka:
    container_name: kafka-server
    image: bitnami/kafka
    networks:
      - av-telemetry
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: unless-stopped
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    #command: bash -c "echo 10000000000000000000000"

  # # Postgres DB (the data store for stream data)
  postgres:
    container_name: postgres
    image: m4ttl33t/postgres:0.0.1           # Can the tag work with 'version'?
    networks:
      - av-telemetry
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mysecretpassword    # Need better password handling

  # # KafkaProducer
  producer:
    container_name: kafka-producer
    image: m4ttl33t/producer:0.0.1           # Can the tag work with 'version'?
    networks:
      - av-telemetry
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - zookeeper
      - kafka

  # KafkaConsumer
  consumer:
    container_name: kafka-consumer
    image: m4ttl33t/consumer:0.0.1           # Can the tag work with 'version'?
    networks:
      - av-telemetry
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - producer
      - postgres

  # # Vehicle (the data streamer)
  vehicle:
    container_name: vehicle         # Programmaticall assign names and many containers?
    image: m4ttl33t/vehicle:0.0.1   # Can the tag work with 'version'?
    restart: unless-stopped
    networks:
      - av-telemetry
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - producer
      - consumer
      - kafka
      - zookeeper